<?php

declare(strict_types=1);

namespace Vendor\LaravelAuthentication\Support;

/**
 * Detects whether mixudev/security-defense is installed and whether its
 * auth event bridge (generated by `php artisan auth:sync`) is wired up.
 *
 * Deliberately uses string-based class checks instead of importing any
 * Mixudev\SecurityDefense class (zero hardcoded coupling invariant).
 */
class SecurityDefenseDetector
{
    public const PROVIDER_CLASS = 'Mixudev\\SecurityDefense\\Providers\\SecurityDefenseServiceProvider';

    /**
     * Whether mixudev/security-defense is installed in the host application.
     */
    public static function isInstalled(): bool
    {
        return class_exists(self::PROVIDER_CLASS);
    }

    /**
     * Whether the bridge subscriber file generated by `auth:sync` exists.
     */
    public static function hasBridgeSubscriber(): bool
    {
        return is_file(app_path('Listeners/AuthenticationSecuritySubscriber.php'));
    }

    /**
     * Whether the bridge subscriber is registered in AppServiceProvider.
     */
    public static function isBridgeRegistered(): bool
    {
        $providerPath = app_path('Providers/AppServiceProvider.php');

        if (! is_file($providerPath)) {
            return false;
        }

        $content = (string) file_get_contents($providerPath);

        return str_contains($content, 'AuthenticationSecuritySubscriber');
    }

    /**
     * Whether integration is fully wired up (package absent counts as wired:
     * nothing to integrate).
     */
    public static function isFullyIntegrated(): bool
    {
        if (! self::isInstalled()) {
            return true;
        }

        return self::hasBridgeSubscriber() && self::isBridgeRegistered();
    }

    /**
     * Integration hint shown after `authentication:install`, or null when
     * security-defense is absent or already fully integrated.
     */
    public static function getStatusMessage(): ?string
    {
        if (! self::isInstalled() || self::isFullyIntegrated()) {
            return null;
        }

        $bridgeCommand = (string) config('authentication.security_defense.bridge_hint', 'php artisan auth:sync');

        $lines = [
            '',
            str_repeat('=', 70),
            '  mixudev/security-defense terdeteksi!',
            '  Jalankan perintah berikut untuk menghubungkan event auth ke SIEM:',
            '',
            '    ' . $bridgeCommand,
            '',
            '  Bridge ini meneruskan event login, lockout, 2FA, device, password,',
            '  dan session ke mesin threat detection & alerting security-defense.',
            str_repeat('=', 70),
            '',
        ];

        return implode(PHP_EOL, $lines);
    }
}
