name: CI Tests & Static Analysis

on:
  push:
    branches: [ main, 1.x ]
  pull_request:
    branches: [ main, 1.x ]

jobs:
  test:
    name: PHP ${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.2, 8.3, 8.4]
        laravel: ['11.*', '12.*']
        dependency-version: [prefer-lowest, prefer-stable]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo, sqlite3, pdo_sqlite, bcmath, json
          coverage: none

      - name: Install Dependencies
        run: |
          composer require "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress

      - name: Validate Composer
        run: composer validate --strict

      - name: Execute Tests
        run: vendor/bin/phpunit --testdox

      - name: Execute Static Analysis
        run: vendor/bin/phpstan analyse --no-progress
